### ISSUE TITLE
TypeError: Cannot match against 'undefined' or 'null'.

### ISSUE THREAD

**Issue by MrOrz** [cofacts/rumors-line-bot#15]
Visible on *desktop version* of LINE bot.

Steps to reproduce:

1. Feed the line bot with a rumor
2. choose a reply
3. When asked "請問這則回應是否有解答原文章", type `y` and send
4. See "糟糕，bot 故障了。可以再傳一次嗎？ QQ" and the following error in rollbar

View details in Rollbar: [https://rollbar.com/mrorz/rumors-line-bot/items/40/](https://rollbar.com/mrorz/rumors-line-bot/items/40/)

```

TypeError: Cannot match against 'undefined' or 'null'.
  File "/app/build/processMessages.js", line 403, in <unknown>
          }`({
  File "native", line unknown, in next
  File "/app/build/processMessages.js", line 19, in step
    function _asyncToGenerator(fn) { return function () { var gen = fn.apply(this, arguments); return new Promise(function (resolve, reject) { function step(key, arg) { try { var info = gen[key](arg); var value = info.value; } catch (error) { reject(error); return; } if (info.done) { resolve(value); } else { return Promise.resolve(value).then(function (value) { step("next", value); }, function (err) { step("throw", err); }); } } return step("next"); }); }; }
  File "/app/build/processMessages.js", line 19, in <unknown>
    function _asyncToGenerator(fn) { return function () { var gen = fn.apply(this, arguments); return new Promise(function (resolve, reject) { function step(key, arg) { try { var info = gen[key](arg); var value = info.value; } catch (error) { reject(error); return; } if (info.done) { resolve(value); } else { return Promise.resolve(value).then(function (value) { step("next", value); }, function (err) { step("throw", err); }); } } return step("next"); }); }; }
  File "/app/node_modules/async-listener/index.js", line 421, in propagateAslWrapper
          nextResult = fn.call(ctx, result);
  File "/app/node_modules/async-listener/index.js", line 458, in <unknown>
              var result = (promise.__asl_wrapper || propagateAslWrapper)(this, fn, val, next);
  File "internal/process/next_tick.js", line 129, in process._tickDomainCallback [as _tickCallback]
```

**Comment by MrOrz** [comment]
Heroku log:

```
2017-05-30T15:23:00.096822+00:00 heroku[router]: at=info method=POST path="/callback" host=rumors-line-bot-staging.herokuapp.com request_id=47746e36-1ada-41f2-8693-705b9c60f5f0 fwd="203.104.146.155" dyno=web.1 connect=1ms service=4ms status=200 bytes=137 protocol=https
2017-05-30T15:23:00.618080+00:00 app[web.1]: [App:heroku-line-bot][Err] GraphQL operation contains error: [ { message: 'userId is not set via query string.',
2017-05-30T15:23:00.618115+00:00 app[web.1]:     locations: [ [Object] ],
2017-05-30T15:23:00.618117+00:00 app[web.1]:     path: [ 'action' ],
2017-05-30T15:23:00.618117+00:00 app[web.1]:     authError: true } ]
2017-05-30T15:23:00.618118+00:00 app[web.1]:
2017-05-30T15:23:00.618790+00:00 app[web.1]: [App:heroku-line-bot][Err] TypeError: Cannot match against 'undefined' or 'null'.
2017-05-30T15:23:00.618792+00:00 app[web.1]:     at /app/build/processMessages.js:403:9
2017-05-30T15:23:00.618792+00:00 app[web.1]:     at next (native)
2017-05-30T15:23:00.618793+00:00 app[web.1]:     at step (/app/build/processMessages.js:19:191)
2017-05-30T15:23:00.618794+00:00 app[web.1]:     at /app/build/processMessages.js:19:361
2017-05-30T15:23:00.618795+00:00 app[web.1]:     at propagateAslWrapper (/app/node_modules/async-listener/index.js:421:23)
2017-05-30T15:23:00.618796+00:00 app[web.1]:     at /app/node_modules/async-listener/index.js:458:70
2017-05-30T15:23:00.618796+00:00 app[web.1]:     at process._tickDomainCallback [as _tickCallback] (internal/process/next_tick.js:129:7)
```

**Comment by MrOrz** [comment]
After setting env variable `APP_SECRET` the error is gone.
